checks:
    php: true

filter:
    paths:
        - "src/*"

tools:
    external_code_coverage: true

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12

            tests:
                override:
                    - php-scrutinizer-run
